version: '2'

services:
  redis:
    image: 'redis:6.2-alpine'
    command: redis-server --requirepass devpassword
    volumes:
      - 'redis:/var/lib/redis/data'
    ports:
      - '6379:6379'

  website:
    build: .
    command: >
      gunicorn 
      -c "python:config.gunicorn" 
      --reload 
      "sanantonioscientist.app:create_app()"
    environment:
      PYTHONBUFFERED: 'true'
    volumes:
      - '.:/sanantonioscientist'
    ports:
      - '8000:8000'

  celery:
    build: .
    command: >
      celery -A sanantonioscientist.blueprints.contact.tasks worker -l info
    env_file:
      - '.env'
    volumes:
      - '.:/sanantonioscientist'

volumes:
  redis:
